[tool.ruff]
fix = true
indent-width = 4
output-format = "full"
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
line-length = 255
target-version = "py312"

[tool.ruff.lint]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
fixable = ["ALL"]
unfixable = [
    # "B", # NAO CORRIGE ERROS flake8-bugbear
    "E402", # NAO CORRIGE ERROS DE IMPORTACAO FORA DO TOPO DO ARQUIVO
    "F401", # NAO CORRIGE ERROS DE IMPORTACAO NAO UTILIZADA
    "B905", # NAO CORRIGE ERROS DE ZIP SEM VALOR DE 'strict'
]
select = ["ALL"]
ignore = [
    "INP001",  # IGNORA FALTA DE __init__.py
    "DTZ001",  # IGNORA FALTA DE TIMEZONE EM FUNCOES DATETIME
    "DTZ005",  # IGNORA FALTA DE TIMEZONE EM FUNCOES DATETIME
    "DTZ007",  # IGNORA FALTA DE TIMEZONE EM FUNCOES DATETIME
    "T201",    # IGNORA USO DE PRINT
    "T203",    # IGNORA USO DE PPRINT
    "D100",    # IGNORA FALTA DE DOCSTRING NOS ARQUIVOS
    "E501",    # IGNORA LINHAS MUITO LONGAS
    "ERA001",  # IGNORA CODIGO COMENTADO
    "PLR2004", # IGNORA USO DE VALOR MAGICO
    "D401",    # IGNORA DOCSTRING NAO ESTAR EM IMPERATIVO
    "S608",    # IGNORA SQL INJECTION
    "TRY002",  # IGNORA CUSTOM EXCEPTION
    "TRY003",  # IGNORA MENSAGENS LONGAS FORA DA CLASSE EXCEPTION
    "E402",    # IGNORA ERROS DE IMPORTACAO FORA DO TOPO DO ARQUIVO
    "E741",    # IGNORA O USO DE CARACTERES AMBIGUOS COMO NOME DE VARIAVEIS

    # "BLE001",
    # "C901", # IGNORA FUNCOES COM ALTA COMPLEXIDADE
    # "A002", # IGNORA ID SOBREPOE PYTHON BUILTIN
    # "A003", # IGNORA ID SOBREPOE PYTHON BUILTIN
    # "W605", # IGNORA SEQUENCIA DE ESCAPE INVALIDA
    # "UP025", # IGNORA O USO DE UNICODE EM STRINGS (PARA PYTHON 2)
    # "UP032", # IGNORA O USO DE FORMAT EM STRINGS (PARA PYTHON 2)
    # "UP009", # IGNORA A PRESENCA DE DECLARACAO UTF-8 NO INCIO DO SCRIPT (PARA PYTHON 2)
    # "UP007", # IGNORA OPTIONAL TYPE HINT
    # "N806" # IGNORA VARIAVEIS EM CAIXA ALTA DENTRO DE FUNCOES
]
[tool.ruff.lint.pylint]
max-args = 10
